language: node_js
node_js:
- 4.1.2
services:
- mongodb
before_install:
- npm install -g grunt-cli
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: X5JNbIFtgosUj0/Ag/SryL0C4AnxDa9H0Q68D7gP3uAOwqh/fzavmzkKR5MtMGZkyJD2cLkN9u9PBfi7nczPZwNOvq8NNzJ3OFdcRXGqcktVv23yw+6C1wsEOQhLgVCiiEOAo1wRXkObfwY+Nrbjsdffa1wcBEnEZ/bOH5vK811ZuH1VBE91+mZoe9dSVO8gc4IqDvXuqQNfZunwPhBu9D68UBxQkUhV0X9gx6WZd62JvRdhwmvbtMEccMwfs6GVKQf/aFmq4nj+cUF1Hk8pj3c5gxNnl53yfakHMfbOvMA5RHr/Y5dt8NMd7llswX0fph8nea+IBQOyrhN5mSeiUBvHwZ8MrEkrn1x5c8QxsxNgCvdbfQgmxEB80I1BmwSdTE16LPFMPU/Hg1B0YfEDWwIFIRYaFk9Q3va0GmuWCniEzTyJKcMzbLBZ2D/gyo8Q4/ZjCESdiD7DbxwnXbTLYxSm4zCB7f+AgUD3XWiKJEjbB5VxRiuIXd50CiXhjnNJf8Izh3xJe1LBhe5vWVceIayvSXGxHPXKvx+aTWdK1NfcOCx4aJ2+CHdnQrj64CzykLvil5K26P9ZkD8QjAgnDfYfqyLxQTmHHeg0uVrd3Rhg12KsmrQUATHaaOQ6mr6YUEA4ZuzJMv767GA5iAttYxsr9i1/xkZkecuO6itfcxg=
  app:
    production: sodocan
    master: sodocan-staging
  on:
    repo: sodocan/sodocan.js
